variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)
  SDK_VERSION: 5.x
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

trigger:
  - master
  - ci-*
  - refs/tags/v*

pr:
  branches:
    include:
      - master

#schedules:
#  - cron: "0 0 * * *"
#    displayName: "Daily midnight build"
#    branches:
#      include:
#        - master

jobs:
  - job: iis_test
    pool:
      vmImage: windows-2019
    steps:
      - checkout: none

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'dir $env:SystemDrive\inetpub\wwwroot'
          errorActionPreference: 'continue'

      - bash: |
          ls -la --color 
          echo "----------------------------------------"
          curl -v http://localhost

      - bash: echo "<html><body>Hello from CI / IIS</body></html>" > web-app/index.html

      - task: IISWebAppManagementOnMachineGroup@0
        inputs:
          #EnableIIS: true      already installed
          IISDeploymentType: 'IISWebsite'
          ActionIISWebsite: 'CreateOrUpdateWebsite'
          WebsiteName: 'Vue_Test_Server'
          WebsitePhysicalPath: '$(Agent.BuildDirectory)\web-app'
          WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
          AddBinding: true
          Bindings: '{"bindings":[{"protocol":"http","ipAddress":"AllUnassigned","port":"5000","hostname":"","sslThumbprint":"","sniFlag":false}]}'
          CreateOrUpdateAppPoolForWebsite: true
          AppPoolNameForWebsite: 'www-test'
          DotNetVersionForWebsite: 'No Managed Code'
          PipeLineModeForWebsite: 'Integrated'
          AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'

      - bash: curl -v http://localhost:5000
