variables:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)
  SDK_VERSION: 5.x
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  DOCKER_IMAGE_NAME: gfoidl-tests/vue-server-tests

trigger:
  - master
  - ci-*
  - refs/tags/v*

pr:
  branches:
    include:
      - master

#schedules:
#  - cron: "0 0 * * *"
#    displayName: "Daily midnight build"
#    branches:
#      include:
#        - master

stages:
  - stage: frontend_build
    jobs:
      - template: jobs/frontend_build.yml

  - stage: frontend_test
    dependsOn: []
    jobs:
      - template: jobs/frontend_test.yml

  - stage: frontend_e2e
    dependsOn:
      - frontend_build
      - frontend_test
    jobs:
      - template: jobs/frontend_e2e.yml

  - stage: backend_build
    dependsOn:
      - frontend_e2e
    jobs:
      - template: jobs/backend_build_and_test.yml

  - stage: docker_build
    dependsOn:
      - backend_build
    jobs:
      - template: jobs/docker_build.yml

  - stage: e2e_test
    dependsOn:
      - docker_build
    jobs:
      - template: jobs/e2e_test.yml
      - template: jobs/e2e_test_iis.yml
      - template: jobs/e2e_test_docker.yml

  - stage: docker_push
    dependsOn:
      - e2e_test
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - template: jobs/docker_push.yml

  - stage: Code_Coverage
    dependsOn:
      - backend_build
    jobs:
      - template: jobs/coverage.yml
