variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)
  SDK_VERSION: 5.x
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

trigger:
  - master
  - ci-*
  - refs/tags/v*

pr:
  branches:
    include:
      - master

#schedules:
#  - cron: "0 0 * * *"
#    displayName: "Daily midnight build"
#    branches:
#      include:
#        - master

jobs:
  - job: iis_test
    pool:
      vmImage: windows-2019
    steps:
      - checkout: none

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'dir $env:SystemDrive\inetpub\wwwroot'
          errorActionPreference: 'continue'

      - bash: |
          ls -la --color 
          echo "----------------------------------------"
          curl -v http://localhost

      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'specific'
          project: 'AzureDevOpsTest'
          definition: '34'
          buildVersionToDownload: 'specific'
          pipelineId: '1387'
          artifactName: 'web-app'
          targetPath: '$(Agent.BuildDirectory)\web-app'

      #- task: IISWebAppManagementOnMachineGroup@0
      #  inputs:
      #    #EnableIIS: true      already installed
      #    IISDeploymentType: 'IISWebsite'
      #    ActionIISWebsite: 'CreateOrUpdateWebsite'
      #    WebsiteName: 'Vue_Test_Server'
      #    WebsitePhysicalPath: '$(Agent.BuildDirectory)\web-app'
      #    WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
      #    AddBinding: true
      #    Bindings: '{"bindings":[{"protocol":"http","ipAddress":"*","port":"5000","hostname":"","sslThumbprint":"","sniFlag":false}]}'
      #    CreateOrUpdateAppPoolForWebsite: true
      #    AppPoolNameForWebsite: 'www-test'
      #    DotNetVersionForWebsite: 'No Managed Code'
      #    PipeLineModeForWebsite: 'Integrated'
      #    AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
      #
      #- task: IISWebAppManagementOnMachineGroup@0
      #  inputs:
      #    IISDeploymentType: 'IISWebsite'
      #    ActionIISWebsite: 'StartWebsite'
      #    StartStopWebsiteName: 'Vue_Test_Server'
      #
      # The above two task "expand" to these steps (here with a little clean-up)
      - task: CmdLine@2
        inputs:
          script: |
            "C:\windows\system32\inetsrv\appcmd.exe"  add apppool /name:"www-test"
            echo --------------------------------------------------
            "C:\windows\system32\inetsrv\appcmd.exe"  set apppool /apppool.name:"www-test" -managedRuntimeVersion: -managedPipelineMode:Integrated -processModel.identityType:ApplicationPoolIdentity
            echo --------------------------------------------------
            "C:\windows\system32\inetsrv\appcmd.exe"  add site /name:"Vue_Test_Server" /physicalPath:"$(Agent.BuildDirectory)\web-app"
            echo --------------------------------------------------
            "C:\windows\system32\inetsrv\appcmd.exe"  set site /site.name:"Vue_Test_Server" -applicationDefaults.applicationPool:"www-test"
            echo --------------------------------------------------
            "C:\windows\system32\inetsrv\appcmd.exe"  set site /site.name:"Vue_Test_Server" /+bindings.[protocol='http',bindingInformation='*:5000:']
            echo --------------------------------------------------
            "C:\windows\system32\inetsrv\appcmd.exe"  list sites
            echo --------------------------------------------------
            "C:\windows\system32\inetsrv\appcmd.exe" start site /site.name:"Vue_Test_Server"
            echo --------------------------------------------------
            "C:\windows\system32\inetsrv\appcmd.exe"  list sites
        displayName: setup IIS-site

      # extension from Marketplace https://marketplace.visualstudio.com/items?itemName=rbosma.InstallNetCoreRuntimeAndHosting
      - task: InstallNetCoreRuntimeAndHosting@1
        inputs:
          version: 5.0
          norestart: true
          iisReset: false

      - task: CmdLine@2
        inputs:
          script: |
            net stop was /y
            net start w3svc

      - bash: curl -v http://localhost:5000
