variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)
  SDK_VERSION: 5.x
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

trigger:
  - master
  - ci-*
  - refs/tags/v*

pr:
  branches:
    include:
      - master

#schedules:
#  - cron: "0 0 * * *"
#    displayName: "Daily midnight build"
#    branches:
#      include:
#        - master

stages:
  - stage: backend_build
    jobs:
      - template: jobs/backend_build_and_test.yml

  - stage: frontend_build
    dependsOn: []
    jobs:
      - template: jobs/frontend_build.yml

  - stage: frontend_test
    dependsOn: []
    jobs:
      - template: jobs/frontend_test.yml

  - stage: Code_Coverage
    dependsOn:
      - backend_build
      - frontend_test
    jobs:
      - template: jobs/coverage.yml
