jobs:
  - job: docker_push
    displayName: docker push to GH-packages
    pool:
      vmImage: ubuntu-18.04
    variables:
      image_name: gfoidl-tests/vue-server-tests
    steps:
      - checkout: none

      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'specific'
          project: 'b917ef97-c76f-4ce5-a20e-a2eb342180cb'
          definition: '34'
          buildVersionToDownload: 'specific'
          pipelineId: '1423'
          artifactName: 'image'
          targetPath: '$(Build.SourcesDirectory)'

      - bash: |
          docker load -i image.tar.gz
          docker tag $DOCKER_IMAGE_NAME docker.pkg.github.com/gfoidl-tests/vue_server_test/web-app:$(Build.BuildId)
          docker tag $DOCKER_IMAGE_NAME docker.pkg.github.com/gfoidl-tests/vue_server_test/web-app:latest

          echo "-------------------------------------------------"
          docker images
        displayName: import docker image

      - bash: |
          echo $GH_TOKEN | docker login docker.pkg.github.com -u gfoidl --password-stdin
          docker push docker.pkg.github.com/gfoidl-tests/vue_server_test/web-app:$(Build.BuildId)
          docker push docker.pkg.github.com/gfoidl-tests/vue_server_test/web-app:latest
          
        displayName: push docker image
        env:
          GH_TOKEN: $(GITHUB_TOKEN)
