jobs:
  - job: docker_build
    displayName: docker build
    pool:
      vmImage: ubuntu-18.04
    variables:
      image_name: gfoidl-tests/vue-server-tests
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          targetPath: ./docker
          artifact: web-app

      - bash: |
          cd docker
          docker build -t $IMAGE_NAME .

          echo "-------------------------------------------------"
          docker images

          echo "-------------------------------------------------"
          cd ..
          docker save -o image.tar.gz $IMAGE_NAME
        displayName: build docker image

      - publish: image.tar.gz
        artifact: image
