jobs:
  - job: docker_push
    displayName: docker push to GH-packages
    pool:
      vmImage: ubuntu-18.04
    variables:
      image_name: gfoidl-tests/vue-server-tests
      GH_TOKEN: $(GH_TOKEN)
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: image
          targetPath: $(Build.SourcesDirectory)

      - bash: |
          docker load -i image.tar.gz

          echo "-------------------------------------------------"
          docker images
        displayName: import docker image

      - task: Docker@2
        inputs:
          containerRegistry: github-gfoidl-tests-docker
          repository: gfoidl-tests/vue_server_test/web-app
          command: push
