jobs:
  - job: docker_build
    displayName: docker build
    pool:
      vmImage: ubuntu-18.04
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          targetPath: ./docker
          artifact: web-app

      - bash: |
          cd docker
          docker build -t gfoidl-tests/vue-server-tests .
        displayName: build docker image

      - bash: docker images
        displayName: show images
