jobs:
  - job: docker_build
    displayName: docker build
    pool:
      vmImage: ubuntu-20.04
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          targetPath: ./docker
          artifact: web-app

      - bash: |
          cd docker
          docker build -t $DOCKER_IMAGE_NAME .

          echo "-------------------------------------------------"
          docker images

          echo "-------------------------------------------------"
          cd ..
          docker save -o image.tar.gz $DOCKER_IMAGE_NAME
        displayName: build docker image

      - publish: image.tar.gz
        artifact: image
