jobs:
  - job: e2e_test
    displayName: e2e tests
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: steps/dotnet-install.yml
      - template: steps/yarn-install.yml

      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: web-app
          targetPath: web-app

      - bash: |
          export WEB_APP_DIR=$(pwd)/web-app
          export ASPNETCORE_CONTENTROOT=$(pwd)/web-app
          export ASPNETCORE_ENVIRONMENT=Development

          cd frontend
          export JEST_PUPPETEER_CONFIG=tests/e2e-full/jest-puppeteer.config.js
          yarn jest --projects tests/e2e-full --verbose --reporters=default --reporters=jest-junit
        displayName: test

      - task: PublishTestResults@2
        condition: always()
        inputs:
          testRunner: JUnit
          testResultsFiles: frontend/junit.xml

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: frontend/logs
          artifactName: logs-e2e-full
      
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: frontend/screenshots-e2e-full
          artifactName: screenshots-e2e-full

      - bash: |
          cd frontend
          chmod +x tests/*.sh

          echo "-------------------------------------------------"
          echo "log-dir:"
          ls -la --color logs
          echo ""
          echo "-------------------------------------------------"

          export VERIFY_LISTEN_ON=1
          export VERIFY_CLIENT_REQUEST=1
          tests/verify-server-logs.sh logs
        displayName: verify server logs
