jobs:
  - job: frontend_e2e
    displayName: frontend e2e tests
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: steps/frontend_packages.yml

      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: wwwroot
          targetPath: backend/source/Server/wwwroot

      - bash: |
          cd frontend
          yarn run test-e2e
        displayName: test

      - task: PublishTestResults@2
        condition: always()
        inputs:
          testRunner: JUnit
          testResultsFiles: frontend/junit.xml

      - task: PublishPipelineArtifact@1
        condition: always()
        displayName: upload screenshots
        inputs:
          targetPath: frontend/screenshots-e2e
          artifactName: screenshots-e2e
