jobs:
  - job: frontend_test
    displayName: frontend unit and component tests
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: steps/yarn-install.yml

      - bash: |
          cd frontend
          yarn run test-coverage
        displayName: test

      - task: PublishTestResults@2
        condition: always()
        inputs:
          testRunner: JUnit
          testResultsFiles: frontend/junit.xml

      - publish: frontend/coverage/cobertura-coverage.xml
        artifact: frontend-coverage
