jobs:
  - job: frontend_build
    displayName: frontend build (production)
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: steps/yarn-install.yml

      - bash: |
          cd frontend
          yarn run build-release
        displayName: build

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: backend/source/Server/wwwroot
          artifactName: wwwroot
