jobs:
  - job: frontend_packages
    displayName: frontend install packages
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: steps/yarn-install.yml

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: frontend/node_modules
          artifactName: node_modules
