jobs:
  - job: server_build
    displayName: server build and test
    pool:
      vmImage: ubuntu-18.04
    strategy:
      matrix:
        debug-build:
          BUILD_CONFIG: Debug
        release-build:
          BUILD_CONFIG: Release
    steps:
      - task: UseDotNet@2
        displayName: 'Use dotnet sdk 5.x'
        inputs:
          version: $(SDK_VERSION)
          includePreviewVersions: true

      - bash: |
          echo 'installed sdks:'
          dotnet --list-sdks
          echo "-------------------------------------------------"
          echo 'environment variables:'
          env | sort

          cd server
          chmod u+x ./build.sh
        displayName: init

      - bash: |
          cd server
          ./build.sh build
        displayName: build

      # coverlet.msbuild must be added as package to the tests
      - bash: |
          cd server
          ./build.sh test-coverage
        displayName: test

      - task: PublishTestResults@2
        condition: always()
        inputs:
          testRunner: VSTest
          testResultsFiles: 'server/**/*.trx'

      - bash: |
            cd server/tests/Coverage

            workDir="$(System.DefaultWorkingDirectory)"

            if [[ "$AGENT_OS" == "Windows_NT" ]]; then
                # Windows needs special treetment for the substitution due the \
                workDir="${workDir//\\/\\\\}\\\\"
            else
                workDir+="/"
            fi

            # Mac has a different sed, so special case it (hooray for standars ;-))
            if [[ "$AGENT_OS" != "Darwin" ]]; then
                sed -i 's|<source>[^<]*</source>|<source>/</source>|g' "Cobertura.xml"
                sed -i "s|${workDir}||g" "Cobertura.xml"
            else
                sed -i '' 's|<source>[^<]+</source>|<source>/</source>|g' "Cobertura.xml"
                sed -i '' "s|${workDir}||g" "Cobertura.xml"
            fi
        displayName: make Cobertura-paths relative

      # shortcut for PublishPipelineArtifact
      # Coverage report will be created later in a different stage
      - publish: server/tests/Coverage/Cobertura.xml
        artifact: 'Coverage-${{ parameters.name }}-$(BUILD_CONFIG)'
